pub mod definition_tests;
pub mod dependency_tests;
pub mod metrics_tests;
pub mod position_tests;
mod registry_tests;
pub mod scope_tests;
mod scope_tree_tests;
mod symbol_table_tests;
pub mod type_system_tests;
pub mod usage_tests;
